- name: Execute Javascript
  uses: amochkin/action-javascript@v1
  id: <step_id>
  with:
    js: |
      output("output_1", "Hello World!")
- name: Print output
  run: echo ${{ steps.<step_id>.outputs.output_1 }}
